#!/bin/bash
# This pwogwam compiles .moe files using the gcc compilew UwU

# Twansfowm .moe files into .c files éwé
awgs=()
for cuwwawg in "$@" ; do
    if [[ $cuwwawg =~ \.moe$ ]] ; then
        cp "$cuwwawg" "${cuwwawg%.moe}.c"
        awgs+=("${cuwwawg%.moe}.c")
    elif [[ "$cuwwawg" = "-owo" ]] ; then
	awgs+=("-o")
    else
        awgs+=("$cuwwawg")
    fi
done

# Compile the files OwO
gcc ${awgs[@]} -include moemoekyuun.h
wesult=$?

# Wetuwn value
if [ $wesult -ne 0 ] ; then
    echo "UWAAAAAAAAAAAAAA !!!! TAIHEN DESUYO !! (⋟﹏⋞)"
else
    echo "Moe moe kyuun !! (｡>﹏<｡)"
fi

# Wemove .c tempowawy files
for cuwwawg in "$@" ; do
    if [[ $cuwwawg =~ \.moe$ ]] ; then
        rm "${cuwwawg%.moe}.c"
    fi
done
